### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by XXN-1N** [lizhuoq/SRGAN#2]
# generator parameters: 1508310
# discriminator parameters: 5215425
  0%|                                                                                                                      | 0/522 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/media/data3/bianjm2/project/SRGAN/main.py", line 116, in <module>
    g_loss.backward()
  File "/home/bianjm2/Data/miniconda3/envs/bianjm/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/bianjm2/Data/miniconda3/envs/bianjm/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

when i ran the train.py, i encountered this problem and don't know how to figure it out.

**Comment by lizhuoq** [comment]
@XXN-1N  The torch version of my project is 1.0. The code can run normally under version 1.0. You can try running it under version 1.0.
